// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using storeAPI.Data;

#nullable disable

namespace storeAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240914214327_SecondChange")]
    partial class SecondChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("storeAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHfamFahLTBWDTLUKhzs6wYtrsZd5HHjmTtA&s",
                            Name = "Grönt te"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://www.healthifyme.com/blog/wp-content/uploads/2020/02/Black-Tea-2-1.jpg",
                            Name = "Svart te"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://kahlstkh.se/wp-content/uploads/2018/03/te-rooibos.jpg",
                            Name = "Rött te"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://sakiproducts.com/cdn/shop/articles/20221107133813-white-tea-recipe-blog_800x800.jpg?v=1667828741",
                            Name = "Vitt te"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/D2E2521B-2690-44B5-8BD5-0BAD5C76EB37/Derivates/290E3C0B-2A82-4243-8C73-BAA412C4CF80.jpg",
                            Name = "Övrigt"
                        });
                });

            modelBuilder.Entity("storeAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caffeine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caffeine = "Låg koffein",
                            CategoryId = 1,
                            Effect = "hjälper till att lugna, förbättra mental klarhet och stärka ditt immunförsvar",
                            Image = "https://blog.piquelife.com/wp-content/uploads/2020/08/Jasmine-Tea-Benefits-5-Research-Backed-Benefits-of-Jasmine-Tea.png",
                            Name = "Jasmine te",
                            Type = "Grönt, svart & vitt"
                        },
                        new
                        {
                            Id = 2,
                            Caffeine = "Medium koffein",
                            CategoryId = 1,
                            Effect = "minska risken för flera kroniska sjukdomar, förbättra uppmärksamhet, minne och reaktionstid",
                            Image = "https://media.post.rvohealth.io/wp-content/uploads/2020/08/matcha-green-tea-732x549-thumbnail.jpg",
                            Name = "Matcha",
                            Type = "Grönt"
                        },
                        new
                        {
                            Id = 3,
                            Caffeine = "Låg koffein",
                            CategoryId = 1,
                            Effect = "Hög koncentration av antioxidanter",
                            Image = "https://www.foodfolder.se/media/5807/img_8874.jpg",
                            Name = "Yogi te green tea matcha lemon",
                            Type = "Grönt"
                        },
                        new
                        {
                            Id = 4,
                            Caffeine = "Låg koffein",
                            CategoryId = 1,
                            Effect = "Renar blodet",
                            Image = "https://htgetrid.com/assets/uploads/2018/03/poleznye-svojstva-i-protivopokazanija-chaja-lunczin.jpg",
                            Name = "Longjing te",
                            Type = "Grönt"
                        },
                        new
                        {
                            Id = 5,
                            Caffeine = "Hög koffein",
                            CategoryId = 2,
                            Effect = "Ökad energi",
                            Image = "https://portfoliocoffee.ca/cdn/shop/articles/benefits-of-earl-grey-tea.jpg",
                            Name = "Earl grey",
                            Type = "Svart"
                        },
                        new
                        {
                            Id = 6,
                            Caffeine = "Hög koffein",
                            CategoryId = 2,
                            Effect = "Fördelar för hjärthälsa",
                            Image = "https://www.thespicehouse.com/cdn/shop/articles/Chai_Masala_Tea_1200x1200.jpg",
                            Name = "Chai te/Masala chai",
                            Type = "Svart (Indiskt)"
                        },
                        new
                        {
                            Id = 7,
                            Caffeine = "Hög koffein",
                            CategoryId = 2,
                            Effect = "Välgörande för huden",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiG0ICI8xUy0Ju5ok6ZsZ49nnKnJ0LG8iSkg",
                            Name = "Litchi",
                            Type = "Svart"
                        },
                        new
                        {
                            Id = 8,
                            Caffeine = "Inget koffein",
                            CategoryId = 3,
                            Effect = "Innehåller antioxidanter",
                            Image = "https://www.thes-traditions.com/img/cms/bienfaits-rooibos.jpg",
                            Name = "Rooibos",
                            Type = "Rött"
                        },
                        new
                        {
                            Id = 9,
                            Caffeine = "Inget koffein",
                            CategoryId = 3,
                            Effect = "Lugnande",
                            Image = "https://media.delitea.se/product-images/XL/arvid-nordquist-skogsglanta-rooibos-17st-2.jpg",
                            Name = "Skogsglänta Rooibos",
                            Type = "Rött"
                        },
                        new
                        {
                            Id = 10,
                            Caffeine = "Inget koffein",
                            CategoryId = 4,
                            Effect = "Lugnande",
                            Image = "https://www.teacultures.com/cache/white-cassis-1_10085/white-cassis-1-800-600-1250-625.jpg",
                            Name = "White Cassis",
                            Type = "Vitt"
                        },
                        new
                        {
                            Id = 11,
                            Caffeine = "Inget koffein",
                            CategoryId = 4,
                            Effect = "Lugnande",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxmRhyN1GjGMoEycRZfpb9b4ahFBlH_H9Vrg",
                            Name = "Jasmin silver needle",
                            Type = "Vitt"
                        },
                        new
                        {
                            Id = 12,
                            Caffeine = "Mellan koffein",
                            CategoryId = 5,
                            Effect = "Förbättrar fettcellernas funktioner",
                            Image = "https://www.schwarzenbach.ch/wp-content/uploads/2023/06/Tee-Oolong-Formosa-Jade-Dung-Tin.jpg",
                            Name = "Formosa Jade Oolong te",
                            Type = "Oolong"
                        },
                        new
                        {
                            Id = 13,
                            Caffeine = "Inget koffein",
                            CategoryId = 5,
                            Effect = "Gynnar nattsömnen",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF3DI1j9GDEJk69X6MyCrCmqXla1B7tlce6w",
                            Name = "Pukka night time",
                            Type = "Örtte"
                        },
                        new
                        {
                            Id = 14,
                            Caffeine = "Mellan koffein",
                            CategoryId = 5,
                            Effect = "Bra för magen",
                            Image = "https://teasenz.eu/cdn/shop/files/gingsheng.jpg?v=1692527694&width=416",
                            Name = "Ginseng Oolongte",
                            Type = "Oolong"
                        },
                        new
                        {
                            Id = 15,
                            Caffeine = "Inget koffein",
                            CategoryId = 5,
                            Effect = "Bra för en rosslig hals",
                            Image = "https://thumbs.dreamstime.com/b/kinesiskt-krysantemumte-p%C3%A5-gammalt-tr%C3%A4-57014906.jpg",
                            Name = "Krysantemumte",
                            Type = "Örtte"
                        });
                });

            modelBuilder.Entity("storeAPI.Models.Product", b =>
                {
                    b.HasOne("storeAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("storeAPI.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
